name: Release Creation

on:
  push:
    paths:
      - "packs/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: fwilhe2/bump-version@main
        id: bump
      - uses: actions/checkout@v3
      - name: Create a Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          title: New Stuff
